### ISSUE TITLE
Looking for documentation / API

### ISSUE THREAD

**Issue by mika-okamoto** [rzshrote/pybrops#79]
Hello, I am a researcher in Dr. Abraham Palmer’s [lab](https://palmerlab.org/) at UC San Diego. I am looking into ways to simulate breeding algorithms to compare how various algorithms retain genetic diversity across generations, and came across your paper. Can you please point me in the right direction for how to run PyBrOpS after installation to simulate breeding across consecutive generations? Any documentation or API or guidance you can provide would be extremely helpful. 

Thank you for any help you can provide, and thanks for your excellent science!
Best, Mika

**Comment by rzshrote** [comment]
Documentation has been generated and is available at [the GitHub Pages website](https://rzshrote.github.io/pybrops/).
